### ISSUE TITLE
Error 127

### ISSUE THREAD

**Issue by vanillamasonry** [geocine/sphinx-se-builds-windows#2]
Dear Aivan,

First of all I want to thank you for your work and fast reply. I have tried to Install the new ha_sphinx.dll build but I receive the following error:

SQL ERROR (1126): Can't open shared library 'C\Program Files\MySQL\MYSQL Server 5.6\lib\plugin\ha_sphinx.dll' (errno 127 The specified procedure could not be found.)

Notes:
OS: Windows 2012 Server
Sphinx service not installed yet.
I must have the sphinx service up in order to load the library ha_sphinx.dll or ha_sphinx.dll has other dependencies ?

Thank you again,
Paul

**Comment by geocine** [comment]
Hi I just need to ask, Did you use the 64 bit version? Thanks.

**Comment by vanillamasonry** [comment]
Yes I use 64 bit MySQL + lib. If I try to load 32 bit lib version I receive err 193 which is correct.
Maybe  ha_sphinx.dll  has other dependencies that are not on my system or is missing something from the interface with MySQL.
Thanks,
Paul

**Comment by geocine** [comment]
@vanillamasonry  thank you for reporting the issue. I may have made a mistake in building it. You may try the new one I have pushed. Also please check if the version installed is 5.6.23 for mysql. Because I have tried downloading the mysql installer for windows 5.6.23 (using web installer) , but it installs  5.6.22-log instead.

**Edit:** this should work now, I installed the correct MySQL 5.6.23 and I have successfully loaded the plugin. Please let me know

**Comment by vanillamasonry** [comment]
I have .23, I have used the ZIP file, not the installer  .....  and YES this one is working! ;)
No loading errors and SPHINX is available as storage engine.
Thank you,
Paul

**Comment by geocine** [comment]
Glad it works now. closing this issue :)
